### ISSUE TITLE
The third step of "Ways to play the game"

### ISSUE THREAD

**Issue by TasneemZh** [stalk-calvin/tetris-game#2]
You mentioned this in README file

> Ways to play the game:
> clone repo: https://github.com/stalk-calvin/tetris-game.git
> cd tetris-game
> run: mvn install exec:java -Dexec.mainClass="tetris.Main"

I wonder how to do the third step, I know at least it has to be done in a cmd (the windows one or Git cmd), but when I copy-paste it, it doesn't work.
I didn't have problems with the first and second step.

I want to apply it because when I run the game in eclipse, the frame seems to be omitted at the end (the last line is omitted of the game frame)

**Comment by stalk-calvin** [comment]
Maven is where the command **mvn** comes from. You will first need to download Maven and install it to be available on your computer (Like how you had to download **git** to do first and second step).

When you have **mvn** command available, command **"mvn install exec:java -Dexec.mainClass="tetris.Main"**" should build and execute the game on your computer where you would be able to play as a Java Application.

**Comment by TasneemZh** [comment]
Great. Now I understand. 
The rest is for me to install this Maven cmd and to deal with it. 
Thanks. I appreciate your help
